public  class GulsahD3 {
    public void ogrenci() {
        system.debug('Yeni bir ogrenci kayit oldu!'); 

    }
 //bu alttakiler variable  
public string firstName;
public string lastName;
private string schoolName = 'Dream School';
public string className;
public boolean art;
public boolean sport;
public integer mathGrade;
public integer engGrade;
public integer scienceGrade;

public void message(){
    System.debug(firstName +' adindabir ogrenci kayit oldu');
}
}
