public class salesForceDeveloper {
    public void myFirstCode() {
       String favCity = 'California';
       String favMovie = 'TrumanShow';
       String favSeason = 'Summer';
       System.debug('Gulsah in en sevdigi sehir '+ favCity+ ' film ' + favMovie + ' mevsim ' +favSeason); 

    }


//SORU 2:
//SalesforceDevoleper adında bir Class oluşturun ve
// bu class, myFirstCode adında bir methoda sahip olsun.
// System.debug yardımı ile methodun içinde 
//favori şehir, film ve mevsiminizi ayrı satırlarda olacak şekilde yazdırın.

//SORU 3:

   //SalesforceDevoleper Class'ında bulunan myFavorites method unun içinde, 
   // biri string diğeri integer iki variable oluşturun. 
   //Bu variablelar favori numaranızı ve bulunduğunuz şehri içersin.
   // System.debug yardımı ile bu variableları örnekteki gibi yazdırın.

public void myFavorite(){

    String myCity ='TX';
    Integer myNum = 39;

    System.debug('Favori numaram--> '+ myNum +'  Bulundugum sehir--> '+ myCity);
}
}