public class StudentDetails {
    public void nameOfStudents() {
        string name = 'Gulsah Cavusoglu';
        system.debug('Student name is'+' '+ name);
        String birthPlace ='Turkey';
        system.debug( birthPlace);
        String like = 'speaking, social medya, reading';
        system.debug(like);
        String place = 'Italy, Germany, India';
        system.debug(name+ ' ' + ' like to visit'+ ' '+ place);
    }
}
